import = [
    "~/.config/alacritty/themes/ayu_dark.toml"
]

[window]

opacity = 0.9

padding.x = 5
padding.y = 5


[font]

normal.family = "Operator Mono Book"
normal.style = "Regular"

bold.family = "Operator Mono Bold"
bold.style = "Bold"

italic.family = "Operator Mono Medium"
italic.style = "Italic"

bold_italic.family = "Operator Mono Medium"
bold_italic.style = "Bold Italic"

size = 16

