- name: Add Neovim ppa
  become: yes
  ansible.builtin.apt_repository:
    repo: "ppa:neovim-ppa/unstable"
    state: present

- name: Update cache
  become: yes
  ansible.builtin.apt:
      update_cache: true

- name: Install Neovim
  become: yes
  ansible.builtin.apt:
      name: neovim
      state: latest
