import = [
    "~/.config/alacritty/themes/ayu_dark.toml"
]

[window]

opacity = 0.9

padding.x = 5
padding.y = 5


[font]

normal.family = "CaskaydiaMono Nerd Font Mono"
normal.style = "SemiLight"

bold.family = "CaskaydiaMono Nerd Font Mono"
bold.style = "SemiBold"

italic.family = "CaskaydiaMono Nerd Font Mono"
italic.style = "SemiLight Italic"

bold_italic.family = "CaskaydiaMono Nerd Font Mono"
bold_italic.style = "SemiBold Italic"

size = 16

