- name: Sync dotfiles
  shell: "stow . --target {{ ansible_env.HOME }} --verbose=2"
  args:
      chdir: "{{ playbook_dir }}/../src"
  register: res
  changed_when: 'res.stderr is search("LINK: ")'
 
