- name: Install Fish
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Set User Shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "/usr/bin/fish"

- name: Setup Fisher
  shell: "curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher"
  args:
    executable: "/usr/bin/fish"

# Assumes the ~/.config/fish/fish_plugins file exists
- name: Install Fish Plugins
  shell: "fisher update"
  args:
    executable: "/usr/bin/fish"
